// Data + i18n strings for UNMAPPED demo

const SEARCH_HITS = [
  {
    id: 'rider',
    informal: 'Bike rider',
    informalNe: 'बाइक राइडर',
    badge: 'NEGATIVE_SPACE',
    isco: '8322',
    formal: 'Car, taxi and van drivers',
    formalNe: 'कार, ट्याक्सी र भ्यान चालक',
  },
  {
    id: 'rider2',
    informal: 'Pathao rider',
    informalNe: 'पठाओ राइडर',
    badge: 'INCLUDED_ALIAS',
    isco: '8322',
    formal: 'Car, taxi and van drivers',
    formalNe: 'कार, ट्याक्सी र भ्यान चालक',
  },
  {
    id: 'delivery',
    informal: 'Khaja delivery boy',
    informalNe: 'खाजा डेलिभरी केटा',
    badge: 'NEGATIVE_SPACE',
    isco: '9621',
    formal: 'Messengers, package deliverers',
    formalNe: 'सन्देशवाहक, प्याकेज वितरक',
  },
  {
    id: 'painter',
    informal: 'House painter',
    informalNe: 'घरको पेन्टर',
    badge: 'INCLUDED_ALIAS',
    isco: '7131',
    formal: 'Painters and related workers',
    formalNe: 'पेन्टर र सम्बन्धित कामदार',
  },
];

const SELECTED = SEARCH_HITS[0]; // Bike rider → 8322

const BRIDGE = {
  regionalBaseline: 20540,        // informal estimate (NRB, ~70% of formal)
  regionalLabel: 'Technicians & Associate Professionals',
  regionalLabelNe: 'प्राविधिक र सहयोगी पेशाकर्मी',
  currentRate: 18000,
  marketRate: 29343,              // formal target potential (NRB verified)
  formalLabel: 'Social Work Associate Professionals',
  formalLabelNe: 'सामाजिक कार्य सहयोगी',
  delta: 11343,
  growthPct: 63,
  unit: '/month',
  source: 'Nepal Rastra Bank · ILO ISCO-08',
  confidence: 94,
  sampleSize: 1247,
};

const SKILLS = [
  { id: 's1', en: 'Hold valid Class A motor vehicle license', ne: 'मान्य कक्षा A सवारी चालक अनुमतिपत्र राख्ने', done: true },
  { id: 's2', en: 'Maintain trip log & GPS-verified route history', ne: 'यात्रा लग र GPS-प्रमाणित मार्ग इतिहास राख्ने', done: true },
  { id: 's3', en: 'Operate digital payment terminal (eSewa, Khalti, FonePay)', ne: 'डिजिटल भुक्तानी टर्मिनल चलाउने', done: true },
  { id: 's4', en: 'Conduct daily pre-trip vehicle safety inspection', ne: 'दैनिक यात्रा-पूर्व सुरक्षा निरीक्षण गर्ने', done: false },
  { id: 's5', en: 'File quarterly income statement with IRD', ne: 'त्रैमासिक आय विवरण IRD मा पेश गर्ने', done: false },
  { id: 's6', en: 'Hold Social Security Fund (SSF) registration', ne: 'सामाजिक सुरक्षा कोष (SSF) दर्ता राख्ने', done: false },
  { id: 's7', en: 'Complete defensive driving certification', ne: 'रक्षात्मक ड्राइभिङ प्रमाणीकरण पूरा गर्ने', done: false },
];

// i18n
const STRINGS = {
  en: {
    appName: 'UNMAPPED',
    tagline: 'Transition Engine',
    greeting: 'Namaste, Bibek',
    greetingSub: 'Find where your work fits in the formal economy.',
    searchLabel: 'What is your current informal skill?',
    searchPlaceholder: 'e.g. house painter, bike rider',
    voiceHint: 'Tap to speak',
    mapsTo: 'Maps to ISCO',
    bridgeTitle: 'The Logic Bridge',
    bridgeSub: 'Your earning gap, mapped to verified market data.',
    yourRate: 'Your actual earnings',
    yourRateHint: 'Enter your rate to see a personalized gap analysis',
    marketRate: 'Formal target potential',
    regionalBaseline: 'Regional baseline (NRB)',
    informalEst: 'Est. informal earnings (70%)',
    nrbVerified: 'NRB verified standard',
    delta: 'Monthly transition opportunity',
    expectedGrowth: 'Expected growth',
    dataConfidence: 'Data confidence',
    verifiedBy: 'Verified by',
    skillsTitle: 'Skill Gap Roadmap',
    skillsSub: 'Tasks required by ISCO-08 for your target occupation.',
    progress: 'Roadmap progress',
    completed: 'completed',
    passportTitle: 'Institutional Passport',
    passportSub: 'Your formalization roadmap, signed and shareable.',
    currentStanding: 'Current Standing',
    transitionTarget: 'Transition Target',
    informal: 'Informal · Excluded',
    formal: 'Formal · Included',
    issuedBy: 'Issued by UNMAPPED Transition Engine',
    documentNo: 'Document No.',
    shareWa: 'Share to WhatsApp',
    export: 'Export PDF',
    perMonth: '/month',
    perDay: '/day',
    perHour: '/hour',
    npr: 'NPR',
    badgeNS: 'Negative Space',
    badgeIA: 'Included Alias',
    badgeNSDesc: 'Detected via gap inference',
    badgeIADesc: 'Direct synonym match',
  },
  ne: {
    appName: 'UNMAPPED',
    tagline: 'ट्रान्जिसन इन्जिन',
    greeting: 'नमस्ते, विवेक',
    greetingSub: 'तपाईंको काम औपचारिक अर्थतन्त्रमा कहाँ बस्छ पत्ता लगाउनुहोस्।',
    searchLabel: 'तपाईंको हालको अनौपचारिक सीप के हो?',
    searchPlaceholder: 'जस्तै घरको पेन्टर, बाइक राइडर',
    voiceHint: 'बोल्न ट्याप गर्नुहोस्',
    mapsTo: 'ISCO मा म्याप',
    bridgeTitle: 'लजिक ब्रिज',
    bridgeSub: 'प्रमाणित बजार डेटासँग तपाईंको आम्दानी अन्तर।',
    yourRate: 'तपाईंको वास्तविक आम्दानी',
    yourRateHint: 'व्यक्तिगत अन्तर विश्लेषणको लागि तपाईंको दर राख्नुहोस्',
    marketRate: 'औपचारिक लक्ष्य सम्भावना',
    regionalBaseline: 'क्षेत्रीय आधार (NRB)',
    informalEst: 'अनौपचारिक अनुमानित आम्दानी (७०%)',
    nrbVerified: 'NRB प्रमाणित मापदण्ड',
    delta: 'मासिक रूपान्तरण अवसर',
    expectedGrowth: 'अपेक्षित वृद्धि',
    dataConfidence: 'डेटा विश्वास',
    verifiedBy: 'प्रमाणित',
    skillsTitle: 'सीप अन्तर रोडम्याप',
    skillsSub: 'तपाईंको लक्षित पेशाका लागि ISCO-08 का आवश्यक कार्यहरू।',
    progress: 'रोडम्याप प्रगति',
    completed: 'पूरा भयो',
    passportTitle: 'संस्थागत पासपोर्ट',
    passportSub: 'तपाईंको औपचारिकीकरण रोडम्याप, हस्ताक्षरित।',
    currentStanding: 'हालको स्थिति',
    transitionTarget: 'रूपान्तरण लक्ष्य',
    informal: 'अनौपचारिक · बहिष्कृत',
    formal: 'औपचारिक · समावेशी',
    issuedBy: 'UNMAPPED द्वारा जारी',
    documentNo: 'कागजात नं.',
    shareWa: 'WhatsApp मा साझा',
    export: 'PDF निर्यात',
    perMonth: '/महिना',
    perDay: '/दिन',
    perHour: '/घण्टा',
    npr: 'रू',
    badgeNS: 'नेगेटिभ स्पेस',
    badgeIA: 'समावेशी उपनाम',
    badgeNSDesc: 'अन्तर अनुमान मार्फत पत्ता लगाइयो',
    badgeIADesc: 'प्रत्यक्ष पर्यायवाची मेल',
  },
};

Object.assign(window, { SEARCH_HITS, SELECTED, BRIDGE, SKILLS, STRINGS });
